# Generated by Django 5.1.6 on 2025-02-27 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Samaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samaj_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=5)),
                ('mobile1', models.CharField(max_length=15)),
                ('mobile2', models.CharField(blank=True, max_length=15, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.family')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='samaj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.samaj'),
        ),
    ]
